### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by MuhammedSaleem-Brej** [prozilla-os/ProzillaOS#14]
root@localhost:~/Downloads/x/node_modules/prozilla-os# pnpm run build

> prozilla-os@1.2.5 build /root/Downloads/x/node_modules/prozilla-os
> tsc --project tsconfig.build.json && vite build

^[[1;3Berror TS5058: The specified path does not exist: 'tsconfig.build.json'.
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
root@localhost:~/Downloads/x/node_modules/prozilla-os#

**Comment by Prozilla** [comment]
Could you please add all the steps you took to get this error? It looks like you're trying to execute the build script inside a compiled version of ProzillaOS, instead of its source code.

**Comment by MuhammedSaleem-Brej** [comment]
Yes, that's correct. I did this initially by mistake, but I edited the comment later. The steps I followed: I cloned the project from the GitHub repository. Then I navigated to the `packages/prozilla-os` directory. After that, I executed the following command: `pnpm build`.

**Comment by Prozilla** [comment]
Please post your errors as code blocks otherwise the formatting gets messed up and the entire thing becomes unreadable. Also please preserve your original comment when editing so future viewers of this issue know the whole context. It looks like you are encountering that issue because you forgot to run `pnpm install`, which is essential to the project.

**Comment by MuhammedSaleem-Brej** [comment]
---

You're right, I hadn't installed the package before.
The steps I took after cloning the project from GitHub are as follows:

```bash
root@localhost:~/Downloads/x# cd Pro*
root@localhost:~/Downloads/x/ProzillaOS-main# pnpm install
```

Summary of the result I got:

```bash
Done in 10.1s
```

Next step:

```bash
root@localhost:~/Downloads/x/ProzillaOS-main# pnpm run packages:build
```

The result I got is as follows:

```bash
 @prozilla-os/monorepo@ packages:build /root/Downloads/x/ProzillaOS-main
> pnpm -r --sequential --filter prozilla-os... build

Scope: 11 of 15 workspace projects

> @prozilla-os/shared@1.1.1 build /root/Downloads/x/ProzillaOS-main/packages/shared
> tsc && vite build

^[[1;3B^[[1;3A^[[1;3B^[[1;3B^[[1;3A^[[1;3A^[[1;3B^[[1;3B^[[1;3A^[[1;3Avite v5.3.1 building for production...
✓ 3 modules transformed.

[vite:dts] Start generate declaration files...
dist/main.js  1.00 kB │ gzip: 0.53 kB │ map: 2.36 kB
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.4.2
^[[1;3B^[[1;3B^[[1;3A^[[1;3A[vite:dts] Declaration files built in 27668ms.

✓ built in 27.95s

> @prozilla-os/skins@1.1.2 build /root/Downloads/x/ProzillaOS-main/packages/skins
> tsc && vite build

^[[1;3B^[[1;3B^[[1;3A^[[1;3A^[[1;3B^[[1;3B^[[1;3A^[[1;3A^[[1;3B^[[1;3B^[[1;3A^[[1;3Afailed to load config from /root/Downloads/x/ProzillaOS-main/packages/skins/vite.config.ts
error during build:
Error: /root/Downloads/x/ProzillaOS-main/node_modules/@ast-grep/napi-linux-arm64-gnu/ast-grep-napi.linux-arm64-gnu.node: undefined symbol: static_assert
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/root/Downloads/x/ProzillaOS-main/node_modules/@ast-grep/napi/index.js:219:31)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
/root/Downloads/x/ProzillaOS-main/packages/skins:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @prozilla-os/skins@1.1.2 build: `tsc && vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
root@localhost:~/Downloads/x/ProzillaOS-main#
```

**Comment by Prozilla** [comment]
Looks like you are trying to run this on Linux, could you please post the specifications of your device/system?

**Comment by MuhammedSaleem-Brej** [comment]
Operating system: "Debian GNU/Linux 11 (bullseye)"
CPU architecture: aarch64
Node version: v20.14.0
When I ran the command "pnpm start" the project worked successfully
I haven't tried modifying any files yet

**Comment by Prozilla** [comment]
Just tested on Ubuntu 22.04.3 LTS on Windows 10 x86_64 and it works fine. I'll try to test on Debian later as well.

Node: v18.12.0

**Comment by Prozilla** [comment]
Seems to be caused by the subdependency `@ast-grep/napi-linux-arm64-gnu` of the dependency `vite-plugin-lib-inject-css`, as you can see in the dependency tree below:

![Dependency tree](https://github.com/user-attachments/assets/b1e2d83b-04e2-4f41-8559-3446cfcc4ab6)

A possible solution would be to fork this plugin and rewrite it without depending on `@ast-grep`.

**Comment by MuhammedSaleem-Brej** [comment]
After running "pnpm run packages:build" I have got this output.
Error: /root/Downloads/x/ProzillaOS-prozilla-os-1.3.11/node_modules/@ast-grep/napi-linux-arm64-gnu/ast-grep-napi.linux-arm64-gnu.node: undefined symbol: static_asser
t
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/root/Downloads/x/ProzillaOS-prozilla-os-1.3.11/node_modules/@ast-grep/napi/index.js:219:31)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)

Comment:

I encountered an error related to the static_assert symbol when attempting to build the project. The error message shows that the symbol static_asser\nt is not defined properly. I tried to correct the name, but it's difficult because the file is in a binary format (*.node), which cannot be edited directly as text.

Would appreciate any guidance or a fix for this issue.

**Comment by Prozilla** [comment]
@MuhammedSaleem-Brej, have you tried running "pnpm install --fix-lockfile"?

**Comment by MuhammedSaleem-Brej** [comment]
Hi,

I tested the latest version and I'm still encountering the same build issue.

After further debugging (with assistance from ChatGPT), I found that the root cause appears to be related to the build order in the monorepo. Specifically, packages like:

@prozilla-os/shared

@prozilla-os/core

are not being built before @prozilla-os/dev-tools, which leads to TypeScript errors such as:

Cannot find module '@prozilla-os/shared' Cannot find module '@prozilla-os/core' 

Manually building the packages in the correct order resolves the issue:

pnpm --filter @prozilla-os/shared build pnpm --filter @prozilla-os/core build pnpm --filter @prozilla-os/dev-tools build 

This suggests that the dependencies between workspace packages may not be properly declared (e.g., missing "workspace:*" entries in package.json), preventing pnpm from determining the correct build order automatically.

It might be worth reviewing the dependency graph or adjusting the build pipeline to ensure proper ordering.

Thanks!
